# Generated by Django 4.2.3 on 2023-08-02 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medapp', '0003_rename_user_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='users',
            field=models.ManyToManyField(through='medapp.UserTopicRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
